[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
pqcrypto = "0.18.0"
pqcrypto-kyber = "0.8.0"
pqcrypto-dilithium = "0.5.0"
pqcrypto-traits = "0.3.5"
rand = "0.8.5"
hex = "0.4.3"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
blake3 = "1.8.2"
chacha20poly1305 = "0.10.1"
ed25519-dalek = { version="2.2.0", features = ["rand_core"] }
thiserror = "2.0.17"
zeroize = "1.8.2"
hkdf = "0.12.4"
sha2 = "0.10.9"
serde = "1.0.228"
